image: registry.modoolar.com/modoolar/devops/images/extended-docker:20.10
stages:
  - build

services:
  - docker:20.10-dind

variables:
  DOCKER_BUILDKIT: 1
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

build:
  stage: build
  variables:
    TAG: "${CI_COMMIT_TAG}"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker --version
  script:
    - docker buildx bake --push --progress=plain
  only:
    - master
    - merge_requests
  tags:
    - docker-dind

